In [2]:
# step#1 importing libraries

import numpy as np
import pandas as pd

In [23]:
# step#2 importing data sets
dataset=pd.read_csv('Data.csv')

In [24]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [25]:
#Dependent Variable (Target / Output) and independent Variable(Features / Input) in data set 
#purchased has no and yes this column is dependent
#all other are independent variables

#x has all independent variable and x is array
X = dataset[['Country','Age','Salary']].values

In [26]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [27]:
#y has all dependent variable and y is array
Y = dataset[['Purchased']].values

In [28]:
Y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [29]:
from sklearn.impute import SimpleImputer

In [30]:
# step#3 finding missing values and replace nan with mean
imp=SimpleImputer(missing_values=np.nan,
              strategy='mean')

In [31]:
imputer= imp.fit(X[:,1:3])

In [32]:
X[:,1:3]=imputer.transform(X[:,1:3])

In [33]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [44]:
# step#4 encoading Categorial data
from sklearn.preprocessing import LabelEncoder

In [45]:
labend= LabelEncoder()

In [46]:
#numerically present country names
X[:,0]=labend.fit_transform(X[:,0])

In [47]:
X  #0 for france, 1 for Germany and 2 for Spain

array([[0, 7, 72000.0],
       [2, 0, 48000.0],
       [1, 1, 54000.0],
       [2, 4, 61000.0],
       [1, 6, 63777.77777777778],
       [0, 2, 58000.0],
       [2, 5, 52000.0],
       [0, 8, 79000.0],
       [1, 9, 83000.0],
       [0, 3, 67000.0]], dtype=object)

In [49]:
from sklearn.preprocessing import OneHotEncoder

onehotencoder = OneHotEncoder()

In [51]:
X= onehotencoder.fit_transform(dataset.Country.values.reshape(-1,1)).toarray()

In [52]:
X

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [53]:
labend_y= LabelEncoder()

In [55]:
#NMERICALLY REPRESENTING PURCHASES
Y=labend_y.fit_transform(Y)

C:\Users\k4kas\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [56]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [70]:
# step#5 splitting dataset into training and test sets
from sklearn.model_selection import train_test_split

In [59]:
x_train,x_test, y_train, y_test  =train_test_split(X,Y,test_size=0.2,random_state=0)

In [60]:
x_train

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [61]:
x_test

array([[0., 1., 0.],
       [0., 1., 0.]])

In [62]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [63]:
y_test

array([0, 0])

In [64]:
from sklearn.preprocessing import StandardScaler

In [65]:
sc_x=StandardScaler()

In [66]:
x_train= sc_x.fit_transform(x_train)

In [67]:
x_test= sc_x.fit_transform(x_test)

In [68]:
x_train

array([[-1.        ,  2.64575131, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667]])

In [69]:
x_test

array([[0., 0., 0.],
       [0., 0., 0.]])