In [ ]:
# Installation (if not already installed)
pip install numpy

In [2]:
#checking version of numpy
import numpy as np
print(np.__version__)

1.26.4


In [31]:
# Create array of zeros
zero=np.zeros((2, 3))  # 2 rows and 3 colmns
print ("Zeros: ",zero)

# Array of ones
one=np.ones((3, 2)) #3 rows and 2 colmns
print("ones: ",one)

# Array with all values as 5
value=np.full((2, 2), 5) #2 rows and 2 colmns all have value 5
print("value: ",value)

# Identity matrix
identity=np.eye(3) #3 rows and 3 colmns
print("identity: ",identity)

# Range of numbers
#start from 0 with increment of 2 and end at number less than 10
range_of_no =np.arange(0, 10, 2)  # [0 2 4 6 8]
print("range of no: ",range_of_no)

# Evenly spaced values
#have 6 number from 0 to 2 with evenly spaced
even_space =np.linspace(0, 2, 6)  # [0.   0.25 0.5  0.75 1. ]
print("even space: ",even_space)

Zeros:  [[0. 0. 0.]
 [0. 0. 0.]]
ones:  [[1. 1.]
 [1. 1.]
 [1. 1.]]
value:  [[5 5]
 [5 5]]
identity:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
range of no:  [0 2 4 6 8]
even space:  [0.  0.4 0.8 1.2 1.6 2. ]


In [34]:
# Random numbers between 0 and 1
random_no =np.random.rand(2, 3) #2 rows and 3 column
print("random no between 0 and 1: ",random_no)

# Random integers between 0 and 10
random= np.random.randint(0, 10, (3, 3)) #3 rows and colmns
print("random integers between 0 and 10: ",random)

random no between 0 and 1:  [[0.29322012 0.13343171 0.86018499]
 [0.41762105 0.34557765 0.08212584]]
random integers between 0 and 10:  [[2 9 1]
 [6 5 5]
 [8 3 9]]


In [17]:
import numpy as np #import library
b=np.array([1,2]) #how to create array using numpy
print("b: ",b)

a=np.array([[1,2,3],[4,5,6]]) #array
print("a: ",a)

print(type(a))

b:  [1 2]
a:  [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [26]:
a=np.array([[1,2,3],[4,5,6]]) #2D array
print("First element of 2D array:",a[0,0])#print first element of 2d array

a[0,0]=10 #changing value
print("After changing:",a)

First element of 2D array: 1
After changing: [[10  2  3]
 [ 4  5  6]]


In [36]:
#array attributes
import numpy as np
a = np.array([[1, 2, 3],[4, 5, 6]]) #array
print("Original array:", a)

# Attribute examples
print("\na.shape        =>", a.shape)        # Shape: (2rows, 3colmns) 
print("a.size         =>", a.size)         # Total elements: 6
print("a.dtype        =>", a.dtype)        # Data type: int64 (platform dependent)
print("a.ndim         =>", a.ndim)         # Number of dimensions: 2

# Method examples
print("\na.max()        =>", a.max())        # Max value: 6
print("a.min()        =>", a.min())        # Min value: 1
print("a.argmax()     =>", a.argmax())     # Index of max in flattened array: 5
print("a.argmin()     =>", a.argmin())     # Index of min in flattened array: 0

# Reshape array or transpose
reshaped = a.reshape(3, 2)
print("\na.reshape(3,2) =>\n", reshaped)     # Reshaped array to (3rows, 2colmns)


Original array: [[1 2 3]
 [4 5 6]]

a.shape        => (2, 3)
a.size         => 6
a.dtype        => int32
a.ndim         => 2

a.max()        => 6
a.min()        => 1
a.argmax()     => 5
a.argmin()     => 0

a.reshape(3,2) =>
 [[1 2]
 [3 4]
 [5 6]]


In [38]:
import numpy as np
a = np.array([10, 20, 30, 50, 60, 70]) #array

#array starting from index 3 to the end.
print(a[3:])

[50 60 70]
