In [ ]:
#operations on arrays in numpy

In [10]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]]) #2D array
print("Original one:",a)

b = a.copy()   #copying array
print("After copying:",b)

Original one: [[1 2 3]
 [4 5 6]]
After copying: [[1 2 3]
 [4 5 6]]


In [8]:
#append and insert in array
result =np.append(a, [[7, 8, 9]], axis=0)  # axis=0 means row and axis 1 means columns
print("after append: ",result)

result =np.insert(a, 1, [10, 20, 30], axis=0)  # Insert at index 1 which is after row 0
print("After insert",result)

after append:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
After insert [[ 1  2  3]
 [10 20 30]
 [ 4  5  6]]


In [12]:
#sorting
a = np.array([[3, 1, 2],
              [9, 7, 8]])
print("before sorting:",a)

result =np.sort(a, axis=1)
print("after sorting:", result)

before sorting: [[3 1 2]
 [9 7 8]]
after sorting: [[1 2 3]
 [7 8 9]]


In [14]:
#deleting
a = np.array([[3, 1, 2],
              [9, 7, 8]])

result =np.delete(a, 0, axis=0)  # Delete first row which is row 0
print("after deleting:",result)

after deleting: [[9 7 8]]


In [17]:
#splitting
x = np.array([1, 2, 3, 4, 5, 6])
result =np.split(x, 3)  # divide into 3 equal arrays
print("After splitting:",result)

z = np.array([[1, 2], [3, 4], [5, 6]])
result =np.vsplit(z, 3) #divide each row in seperate array
print("After splitting 2d array:",result)


After splitting: [array([1, 2]), array([3, 4]), array([5, 6])]
After splitting 2d array: [array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


In [ ]:
#Data Loading & Saving
np.save('array.npy', a)  # Binary format
np.savetxt('array.txt', a)  # Text format

#loading array
np.load('array.npy')
np.loadtxt('array.txt')

In [19]:
#NumPy Indexing and Selection
a = np.array([[1, 2, 3], [4, 5, 6]])
b=a[0, 1]  # 2 (row 0, col 1)
print (b)

b=a[1]     # [4 5 6] (2nd row)
print(b)


2
[4 5 6]


In [21]:
#logical selection
a = np.array([10, 20, 30, 40])
a[a > 25]  # [30 40]

array([30, 40])

In [24]:
#Broadcasting
a = np.array([1, 2, 3])
b=a + 5  # [6 7 8]
print(b)

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([1, 0, 1])
C=A + B  # [[2 2 4], [5 5 7]]
print("\n",C)

[6 7 8]

 [[2 2 4]
 [5 5 7]]


In [25]:
#typecasting------->converting one data type to another.
import numpy as np

a = np.array([1.2, 3.4, 5.6])
print(a.dtype)          #datatype

# Convert float to int
b = a.astype(int)   #typecasting
print(b)                # [1 3 5]
print(b.dtype)          #datatype


float64
[1 3 5]
int32


In [27]:
#Arithmetic Operations
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

result =a + 5       
print("After adding 5:",result)

result =a * 2  
print("After multiplyingby 2:",result)

result =a - b 
print("After subtracting:",result)

result =a / b
print("After dividing:",result)

result =a % b
print("Modulus:",result)

result =a // b
print("float divide:",result)

result =a ** b
print("exponent:",result)

After adding 5: [15 25 35]
After multiplyingby 2: [20 40 60]
After subtracting: [ 9 18 27]
After dividing: [10. 10. 10.]
Modulus: [0 0 0]
float divide: [10 10 10]
exponent: [   10   400 27000]


In [28]:
#Universal Array Functions
x = np.array([1, 4, 9, 16])

result=np.sqrt(x)
print(result)

result=np.exp(x)
print(result)

result=np.log(x)	
print(result)

result=np.sin(x)
print(result)

result=np.cos(x)
print(result)

result=np.abs(x)	
print(result)

result=np.power(x, 2)
print(result)

[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[0.         1.38629436 2.19722458 2.77258872]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948]
[ 1  4  9 16]
[  1  16  81 256]
